config/routes.rb
Blaw::Application.routes.draw do
  root :to => "home#about"
  get "about" => "home#about"
  get "attorneys" => "home#attorneys"
  get "practice_areas" => "home#practice_areas"
  get "contact" => "home#contact"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about

  end

  def attorneys

  end

  def practice_areas

  end

  def contact

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h2>About Us</h2>

<p>Our purpose is to provide professional, responsive representation to our clients in their important legal 	matters. Our specialty is the effecient, professional, cost effective handling of high volume, small balance, 	consumer collections.
</p>
	
<p>We have developed systems which allow us to collect a much greater percentage of such cases than is possible 	through non-judicial collection methods. We have proven this over twenty years and in tens of thousands of 	     	cases. The availability of judicial remedies allows us to treat the debtors respectfully with no loss of 	efficiency
</p>

app/views/home/attorneys.html.erb
<h3>Kendall S. Peterson</h3>
<ul class="thumbnails">
	<li class="span4">
	<div class="thumbnail">
		<a href="#" class="thumbnail">
		<img src="holder.js/300x200" width="300" height="200" alt="Picture of Kendall S. Peterson">
		</a>
		<a href="mailto:b.nykamp@legalut.com">k.peterson at legalut.com</a>
		</div>
	</li>
	
</ul>

<h3>Bradley G. Nykamp</h3>
<ul class="thumbnails">
	<li class="span4">
	<div class="thumbnail">
		<a href="#" class="thumbnail">
		<img src="holder.js/300x200" width="300" height="200" alt="Picture of Bradley G. Nykamp">
		</a>
		<a href="mailto:b.nykamp@legalut.com">b.nykamp at legalut.com</a>
		</div>
	</li>

</ul>

app/views/home/contact.html.erb
<div id="contactus">
<address>
	<h1><strong>Peterson Nykamp Law</strong></h1><br>
	5383 South 900 East, Suite 205<br>
	Salt Lake City, Utah 84117<br>
	<abbr title="Phone">Telephone</abbr> (801) 261-2220<br>
	<abbr title="Phone">Facsimile</abbr> (801) 261-2230
</address>

<form>
  <fieldset>
    <legend>Contact Us</legend>
    <label>First Name </label>
    <input type="text" placeholder="First Name…">
    <label>Last Name</label>
    <input type="text" placeholder="Last Name…">
    <label>Email</label>
    <input type="text" placeholder="Email…">
    <label>Phone Number </label>
    <input type="text" placeholder="Phone Number…">
    <span class="help-block"></span>
    
    <button type="submit" class="btn">Submit</button>
  </fieldset>
</form>
</div>

<img src="http://maps.googleapis.com/maps/api/staticmap?center=40.653978,-111.865346&zoom=16&size=550x550&markers=color:blue%7Clabel:S%7C40.653978,-111.865346&sensor=false">

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/practice_areas.html.erb
<h1>Practice Areas Page</h1>

<ul>
	<li>Creditors</li>
<li>Consumer And Commercial Debt Collection</li>
<li>Foreclosure</li>
<li>Judgment Collection</li>
<li>Business Formation & Planning</li>
<li>Contract Formation and Litigation</li>
<li>Personal Injury</li>
<li>Divorce</li>
<li>Estate Planning- Wills, Trusts & Probate</li>
<li>Criminal Defense</li>
</ul>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="brand">
<a href="/about"><%= image_tag "logo.png" %></a>

<%#= link_to "Peterson | Nykamp", root_path, :class => "brand" %>
<%= link_to "Peterson Nykamp Law", about_path, :class => "brand subtitle" %>
</div>

<ul class="nav pull-right">
	<li><%= link_to 'About Us', about_path, :class => "about" %></li>
	<li><%= link_to 'Attorneys', attorneys_path, :class => "attorneys" %></li>
	<li><%= link_to 'Practice Areas', practice_areas_path, :class => "practice" %></li>
	<li><%= link_to 'Contact', contact_path, :class => "contact" %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Peterson & Nykamp Attorneys at Law" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Blaw" %>">

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" type="text/css" href="assets/css/bootstrap-responsive.css">
    <%= yield(:head) %>
    <script src="app/assets/javascripts/holder.js"></script>
  
  
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top navbar-inverse">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
      
    </div>

    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>